extends:
  - eslint:recommended
  - standard
rules:
  no-unused-vars: ['error', {vars: 'all', args: 'all', argsIgnorePattern: '^_'}]
  prefer-const: error
  no-var: error
  no-multiple-empty-lines: [error, {"max": 3, "maxEOF": 0}]
  no-trailing-spaces: error
  semi: ['error', 'never']
  comma-dangle: ['error', 'always-multiline']
env:
  browser: true
